version: "3.9"

services:
  auth-db:
    image: postgres:15
    container_name: auth-db
    env_file:
      - ./services/auth_service/.env.db
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auth-service:
    build: ./services/auth_service
    container_name: auth-service
    command: >
      sh -c "python wait_for_db.py &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./services/auth_service:/app
    ports:
      - "8000:8000"
    env_file:
      - ./services/auth_service/.env
    depends_on:
      - auth-db

volumes:
  auth_db_data:
